# Permalinks
permalink:           pretty

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
paginate:            5
excerpt_separator:   <!--more-->

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Comments
disqus:
  shortname:         mydisqus # enter this from your disqus account

# Compress HTML (using the magical compress.html file!)
compress_html:
  clippings:         all
  comments:          all
  blanklines:        false

social:
  facebook:          myfacebook
  twitter:           mytwitter
  # google:            mygoogle
  # instagram:         myinstagram
  # pinterest:         mypinterest
  # linkedin:          mylinkedin
  # youtube:           myyoutube
  # spotify:           myspotify
  github:            mygithub
  # lastfm:            mylastfm
  # stackoverflow:     9999999/username
  # quora:             userquora
  # reddit:            username
  # medium:            medium
  # vimeo:             myvimeo

# Compress SASS
sass:
  style:             compressed

gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

