# Permalinks
permalink:           pretty

# Setup
title:               Jocelyn Legault
tagline:             'The public parts'
description:         'A repository of thoughts and experiments.'
url:                 https://jocelyn.legau.lt
lang:                en_CA
timezone:            America/Montreal
twitter:
  username:          jocelynlegault
paginate:            5
excerpt_separator:   <!--more-->

# About/contact
author:
  twitter:           jocelynlegault
  name:              Jocelyn Legault
  url:               https://jocelyn.legau.lt
  email:             jocelynlegault@gmail.com
  picture:           /assets/img/joce-face.jpg

# Comments
disqus:
  shortname:         jocelynlegault # enter this from your disqus account

# Compress HTML (using the magical compress.html file!)
compress_html:
  clippings:         all
  comments:          all
  blanklines:        false

social:
  name:              Jocelyn Legault
  links:
    - https://twitter.com/jocelynlegault
    - https://github.com/joce
    - https://stackoverflow.com/users/82682/joce
    - https://www.linkedin.com/in/jocelyn-legault-b22642/
  # facebook:          myfacebook
  # twitter:           mytwitter
  # google:            mygoogle
  # instagram:         myinstagram
  # pinterest:         mypinterest
  # linkedin:          mylinkedin
  # youtube:           myyoutube
  # spotify:           myspotify
  github:            joce
  # lastfm:            mylastfm
  stackoverflow:     82682/joce
  # quora:             userquora
  # reddit:            username
  # medium:            medium
  # vimeo:             myvimeo

google_site_verification: ahELMuJq93oFwiOBhJIzC6WQjH-Wg9thjceCcZVuOWo

# Compress SASS
sass:
  style:             compressed

gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
